
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Kursach
{

using System;
    using System.Collections.Generic;
    
public partial class Ingredient
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Ingredient()
    {

        this.IngridientsProducts = new HashSet<IngridientsProduct>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public int Group { get; set; }

    public decimal Weight { get; set; }



    public virtual IngredientType IngredientsTypes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<IngridientsProduct> IngridientsProducts { get; set; }

}

}
