//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.ProductsOrders = new HashSet<ProductsOrder>();
        }
    
        public int Id { get; set; }
        public int Discount { get; set; }
        public bool IsCompleted { get; set; }
        public System.DateTime OrderDate { get; set; }
        public bool IsGiven { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsOrder> ProductsOrders { get; set; }

        public double Total
        {
            get
            {
                decimal cost = 0;

                using (KursachDBContext context = new KursachDBContext())
                {
                    foreach (ProductsOrder item in context.ProductsOrders.Where(po => po.OrderId == this.Id))
                    {
                        cost += item.Products.Price;
                    }
                }

                return Convert.ToDouble(cost);
            }
        }
    }
}
