
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Kursach
{

using System;
    using System.Collections.Generic;
    
public partial class ProductsOrder
{

    public int id { get; set; }

    public int ProductId { get; set; }

    public int OrderId { get; set; }



    public virtual Order Orders { get; set; }

    public virtual Product Products { get; set; }

}

}
